In [1]:
import pandas as pd

In [3]:
dfBboxes = pd.read_csv('./luna_bboxlist.csv')
dfDatapath = pd.read_csv('./luna_datapath.csv')

In [13]:
dfBboxes[dfBboxes['from_subset']==0]

,Unnamed: 0,filename,bbox,npz_path,from_subset
0,0,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[85.4213676, 102.70280896, 202.88853569, 13.59...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
1,1,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[70.6780888, 131.07166564999997, 193.09204143,...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
2,2,1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981...,"[76.530798, 151.49522379999996, 239.3064383700...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.3...,0
3,3,1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686...,"[226.770425, 187.98823521999998, 85.1026149499...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
4,4,1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686...,"[204.7610544, 171.70929114999998, 195.32300902...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
...,...,...,...,...,...
107,107,1.3.6.1.4.1.14519.5.2.1.6279.6001.250863365157...,"[205.0926105, 73.98890039, 80.48566197, 10.061...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
108,108,1.3.6.1.4.1.14519.5.2.1.6279.6001.219909753224...,"[170.7213159, 104.24704104, 224.4234819, 13.84...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
109,109,1.3.6.1.4.1.14519.5.2.1.6279.6001.219909753224...,"[233.90311113, 150.55314921000002, 205.4293993...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
110,110,1.3.6.1.4.1.14519.5.2.1.6279.6001.832260670372...,"[88.20633939999999, 190.97395179, 50.695464099...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.8...,0
111,111,1.3.6.1.4.1.14519.5.2.1.6279.6001.832260670372...,"[222.66391873999999, 146.28895442, 200.6272407...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.8...,0

In [ ]:
1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059.npz

1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686363159853715266493.npz

1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261026510628926082729.npz

1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981831854739626597495.npz

1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896446896160048741492.npz

1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640021803112060161074.npz

In [16]:
dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059.npz']

,Unnamed: 0,filename,bbox,npz_path,from_subset
0,0,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[85.4213676, 102.70280896, 202.88853569, 13.59...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
1,1,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[70.6780888, 131.07166564999997, 193.09204143,...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0

In [22]:
new_dfBboxes = pd.concat([dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059.npz'],
                          dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686363159853715266493.npz'],
                          dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261026510628926082729.npz'],
                          dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981831854739626597495.npz'],
                          dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896446896160048741492.npz'],
                          dfBboxes[dfBboxes['npz_path']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640021803112060161074.npz']    
],ignore_index=True)

In [23]:
new_dfBboxes

,Unnamed: 0,filename,bbox,npz_path,from_subset
0,0,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[85.4213676, 102.70280896, 202.88853569, 13.59...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
1,1,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,"[70.6780888, 131.07166564999997, 193.09204143,...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
2,3,1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686...,"[226.770425, 187.98823521999998, 85.1026149499...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
3,4,1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686...,"[204.7610544, 171.70929114999998, 195.32300902...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
4,5,1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261...,"[212.33100770000004, 146.25810369999996, 53.51...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
5,6,1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261...,"[47.05204700000013, 172.96396470000002, 57.622...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
6,2,1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981...,"[76.530798, 151.49522379999996, 239.3064383700...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.3...,0
7,7,1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896...,"[81.933381, 166.26051683000003, 43.93205550000...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...,0
8,10,1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640...,"[176.60783660000016, 42.133466500000026, 166.4...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
9,11,1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640...,"[81.11608430000001, 134.47071839999995, 221.27...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0
10,12,1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640...,"[189.66359039999998, 117.93442519999999, 208.2...",./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...,0

In [24]:
new_dfDatapath = pd.concat([dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059.npz'],
                          dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686363159853715266493.npz'],
                          dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261026510628926082729.npz'],
                          dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981831854739626597495.npz'],
                          dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896446896160048741492.npz'],
                          dfDatapath[dfDatapath['filePath']=='./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640021803112060161074.npz']    
],ignore_index=True)

In [25]:
new_dfDatapath

,filename,filePath
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.188209889686...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.219087313261...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.303421828981...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.3...
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.1...
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.213140617640...,./luna_npy/1.3.6.1.4.1.14519.5.2.1.6279.6001.2...

In [26]:
new_dfBboxes.to_csv('new_luna_bboxlist.csv')

In [27]:
new_dfDatapath.to_csv('new_luna_datapath.csv')

In [31]:
Union[12,1]

NameError: name 'Union' is not defined

In [32]:
from typing import Union

In [33]:
Union[12,1]

TypeError: Union[arg, ...]: each arg must be a type. Got 12.

In [36]:
[].append([1,3])